version: '3'

services:

  php:
    image: php:7.4-apache
    container_name: php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/c/projetos/php:/var/www/html
    links:
      - db

  db:
    image: mysql:latest
    container_name: mysql
    ports: 
      - "3306:3306"
    volumes: 
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root 